name: Continuous Delivery Pipeline
'on':
  push:
    branches:
      - master
jobs:
  deployingProd:
    name: Deployment to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenShift Actions
        uses: redhat-actions/oc-installer@v1
        with:
          version: 3.11.230
      - name: Executing OC Commands
        run: >
          #!/bin/bash

          repoName=`echo ${{ github.event.repository.name }} | sed -e
          's/[^a-z0-9]//g'`

          oc login --token=${{ secrets.OC_API_TOKEN }} --server=${{
          secrets.OC_SERVER_URL }}

          oc start-build $repoName --follow || oc new-app
          https://www.github.com/${{ github.repository }} --name=$repoName
