name: CI/CD Workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v

name: Format to PEP 8
on: [push]
id: autopep8
uses: peter-evans/autopep8@v1
with:
  args: --recursive --in-place --aggressive --aggressive