name: OpenShift Actions

on: [push, pull_request]
# branches:
#     - master

jobs:
  openShiftSetup:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: OpenShift Actions
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
            version: 'latest'
        - name: OC Commands
        run: |
            oc login --token=${{ secrets.API_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
            oc get pods | grep build