name: PyTest

on: push

jobs:
  pyTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Installing Python dependencies from requirements.txt
      uses: py-actions/py-dependency-install@v2
      with:
        path: "./requirements.txt"
    - name: Test with pytest
      run: |
        pytest -vv --cov=backend/resources --cov-fail-under=90 -W ignore::DeprecationWarning