name: PyTest

on: [push]

jobs:
  pyTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pip install flask
        pip install flask-restful
        pip install flask-cors
        pytest -vv --cov=backend/resources --cov-fail-under=90 -W ignore::DeprecationWarning