name: Python Pylin GitHub Action
on:
  push:
    paths:
      - '**.py'
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: fylein/python-pytest-github-action@v2
      with:
        args: pip3 install -r pytest test/unit