name: GitHub Action for PyTest
uses: cclauss/GitHub-Action-for-pytest@0.5.0
on:
  push:
    paths:
      - '**.py'
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: cclauss/GitHub-Action-for-pytest@0.5.0
        name: PyTest for Flask
        run: pytest