name: PyTest
on:
  push:
    paths:
      - '**.py'
jobs:
  build:
    runs-on: ubuntu-latest
    name: PyTest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.1.0
    - name: Python Pylin GitHub Action
      uses: fylein/python-pytest-github-action@v2
      with:
        args: pip3 install -r pytest test/unit