name: PyTest
on:
  push:
    paths:
    - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - name: Test with pytest
        run: pytest -vv